### PR TITLE
fix ping_islandora

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
starting to work on getting jExcel setup as an editor in the workbench and saw this little bit that I fixed.

### CODE REVIEW

**Comment by mjordan** [comment]
Super! Thanks for taking a look. Can't test at the moment since our campus is suffering a power outage, but I'll test tonight!

**Comment by mjordan** [comment]
@seth-shaw-unlv this is further along than I got for sure, but when Islandora is not responding (e.g. not running), the `ping_islandora()` function is still returning `true`, whereas the intent is for it to return `false`. I don't understand why that is, since `if (error)` should be true at that point. Am I reading that logic wrong?

**Comment by seth-shaw-unlv** [comment]
🤔 It should return false for anything other than a 200 response. I'll poke at it in the morning.

**Comment by seth-shaw-unlv** [comment]
Oh, wait, perhaps we needed to return the value of the http.get call too... that would make sense: the get call is executing the anon function and returning the false value which we neither store in a variable nor return as the result of the islandora_ping function.  I can test tomorrow if you don't get to it first.

**Comment by seth-shaw-unlv** [comment]
Quickly edited the PR with sleeping baby in arms. Suffice it to say, the fix is untested.

**Comment by seth-shaw-unlv** [comment]
Nope, that logic is wrong too, since we are simply returning the [Client Request](https://nodejs.org/api/http.html#http_class_http_clientrequest) (see [get documentation](https://nodejs.org/api/http.html#http_http_get_url_options_callback)). I'll keep looking at it.

**Comment by seth-shaw-unlv** [comment]
Oh, Javascript... so, the key is to turn ping_islandora into a promise using async and await. Once the promise returns then we can carry on our merry way. PR update incoming.

**Comment by mjordan** [comment]
This is a lot better than what I tried. I'll merge and then delete the line `console.log(jsonApiJson)`. Thanks!

**Pull request merged**
