### PR TITLE
jExcel WIP

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
Gets a working editor window that will load from a list of available content types (assumes localhost:8000/jsonapi) and selected directory of files.

Yes, there is still a lot to do, but it is something to look at for the time being....

### CODE REVIEW

**Comment by mjordan** [comment]
Super! I'm currently on vacation but will find time to kick this PR's tires in the next couple of days.

**Comment by seth-shaw-unlv** [comment]
No worries. Like I said, there is a _lot_ that needs to get it in a workable condition. E.g. I need to pass the config settings instead of hard-coding them and we still need to be able to pass the completed CSV to the workbench to do the actual loading...

I'll keep plugging away at it.

**Comment by mjordan** [comment]
@seth-shaw-unlv was going to ask you today but forgot - is this ready for testing/demo? No sweat if not, I can demo current master next week.

**Comment by seth-shaw-unlv** [comment]
@mjordan, kinda? With [my working branch](https://github.com/seth-shaw-unlv/islandora_workbench_desktop/tree/jexcel):

- As before, we can generate a spreadsheet view from the selected content type (although the first load button push always fails but then works on the second time; I have no idea why) 
- We can select a directory of files to populate their paths and file extents.
- We can then edit the spreadsheet (although there are some quirks that need fixing). 
- Clicking the 'Save' button which will drop a CSV on the filesystem.

However, I haven't had a chance to generate the necessary config to pass it off to the workbench for upload. _So close to a working alpha!_ But other project priorities forced me to back burner closing that gap.

Once we close that gap I can start with the derivative generation and item-view.

XKCD web-comic 'Data Pipeline'; the 'giant house of cards' is apropos for our level of development right now. [XKCD: Data Pipeline](https://xkcd.com/2054/)

**Comment by mjordan** [comment]
No sweat - I'm happy to toy around with setting the csv path in the config if you want, but not until this weekend. Thanks for the XKCD!

**Comment by mjordan** [comment]
@seth-shaw-unlv I've resolved a minor conflict, and merged your branch into master, and everything installs fine. Firing up the editor shows a security warning, but other than that, it appears to work as you describe above.

I'll add a note to the README to say the editor component is still a WIP. 

Thanks! This is exciting!

**Pull request merged**
